# Generated by Django 3.0.9 on 2020-08-19 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0002_error_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Вакансия', 'verbose_name_plural': 'Вакансии'},
        ),
    ]
