# Generated by Django 3.0.9 on 2020-08-08 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0002_auto_20200808_2124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
    ]
